/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package econosyncapp;

/**
 *
 * @author jeros
 */
public class Login extends javax.swing.JFrame {
    private User us;
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        setLocationRelativeTo(null);//Hace que la ventana aparesca en el centro
        us = new User(this);//Creando un objeto de la clase user
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jToggleButton1 = new javax.swing.JToggleButton();
        PasswordText = new javax.swing.JLabel();
        PasswordField = new javax.swing.JPasswordField();
        InciarButton = new javax.swing.JButton();
        UserImg = new javax.swing.JLabel();
        Aprovacion = new javax.swing.JLabel();
        Bg = new javax.swing.JLabel();

        jCheckBox1.setText("jCheckBox1");

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PasswordText.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        PasswordText.setForeground(new java.awt.Color(255, 255, 255));
        PasswordText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PasswordText.setText("PASSWORD");
        getContentPane().add(PasswordText, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 350, 20));

        PasswordField.setBackground(new java.awt.Color(0, 0, 29));
        PasswordField.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        PasswordField.setForeground(new java.awt.Color(255, 255, 255));
        PasswordField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PasswordField.setBorder(new javax.swing.border.MatteBorder(null));
        PasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordFieldActionPerformed(evt);
            }
        });
        getContentPane().add(PasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, 200, 50));

        InciarButton.setBackground(new java.awt.Color(0, 0, 43));
        InciarButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        InciarButton.setForeground(new java.awt.Color(255, 255, 255));
        InciarButton.setText("Log In");
        InciarButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        InciarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InciarButtonActionPerformed(evt);
            }
        });
        getContentPane().add(InciarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 460, 200, 50));

        UserImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/econosyncapp/imagenes/UserImg.png"))); // NOI18N
        getContentPane().add(UserImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, 260));

        Aprovacion.setForeground(new java.awt.Color(255, 255, 255));
        Aprovacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(Aprovacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, 310, 30));

        Bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/econosyncapp/imagenes/BgLogin.jpeg"))); // NOI18N
        Bg.setText("jLabel2");
        Bg.setMaximumSize(new java.awt.Dimension(1080, 1920));
        Bg.setMinimumSize(new java.awt.Dimension(1080, 1920));
        getContentPane().add(Bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordFieldActionPerformed
        String passwordInput = new String(PasswordField.getPassword());
        if(!us.login(passwordInput))
        {
            Aprovacion.setText("Contraseña Incorrecta");
            PasswordField.setText("");
        }
    }//GEN-LAST:event_PasswordFieldActionPerformed

    private void InciarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InciarButtonActionPerformed
        
        String passwordInput = new String(PasswordField.getPassword());
        if(!us.login(passwordInput))
        {
            Aprovacion.setText("Contraseña Incorrecta");
            PasswordField.setText("");
        }
        
    }//GEN-LAST:event_InciarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Aprovacion;
    private javax.swing.JLabel Bg;
    private javax.swing.JButton InciarButton;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JLabel PasswordText;
    private javax.swing.JLabel UserImg;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
